import { ERROR_CODES } from "./error-codes.js";

export const EXIT_CODES = {
  OK: 0,
  GENERAL_ERROR: 1,
  CONFIG_ERROR: 2,
  NETWORK_ERROR: 3,
  TIMEOUT_ERROR: 4,
  PARAMETER_ERROR: 5,
};

const ERROR_TO_EXIT = {
  [ERROR_CODES.CONFIG]: EXIT_CODES.CONFIG_ERROR,
  [ERROR_CODES.NETWORK]: EXIT_CODES.NETWORK_ERROR,
  [ERROR_CODES.TIMEOUT]: EXIT_CODES.TIMEOUT_ERROR,
  [ERROR_CODES.PARAMETER]: EXIT_CODES.PARAMETER_ERROR,
  [ERROR_CODES.UNKNOWN]: EXIT_CODES.GENERAL_ERROR,
};

export function toExitCode(errorCode) {
  return ERROR_TO_EXIT[errorCode] ?? EXIT_CODES.GENERAL_ERROR;
}
